branch-defaults:
  master:
    environment: handson-2150005-production
    group_suffix: null
  staging:
    environment: handson-2150005-staging
global:
  application_name: handson-2150005
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: ap-northeast-1
  profile: eb-cli
  sc: git
